### ISSUE TITLE
ExtendScript Toolkit opens up...

### ISSUE THREAD

**Issue by deraalex** [Eliepse/AfterEffectsScript-Explode-Shape-Layer#1]
ExtendScript Toolkit opens up everytime i click on "explode layer" in After Effects Version 17.0.0
Script works anyway.

**Comment by Eliepse** [comment]
Hi,

Sorry to hear that.
Could you tell me how you proceed to install and/or run the script?

**Comment by Eliepse** [comment]
Due to the inactivity, I close this issue. Feel free to reopen it.
