### ISSUE TITLE
stuck at "processing element 5 on 42"

### ISSUE THREAD

**Issue by merepapa** [Eliepse/AfterEffectsScript-Explode-Shape-Layer#2]
i have tried this on 2020, 2018 deleting the element 5 or doing it on any other shape layer it's always getting stuck at 5
![image](https://user-images.githubusercontent.com/82329144/130730789-1c089a79-14ef-4330-8210-5731e1d97207.png)

removing some settings group and grouping each line in its own group didnt help
![image](https://user-images.githubusercontent.com/82329144/130731539-85d332eb-876b-409b-a067-b74b9ae77bd3.png)

**Comment by Eliepse** [comment]
Hi, thank you for sharing your problem.
Can you share with the element you tried to "explode", if it is possible ?
I didn't work on this plugin for a long time, but I will try to assist you :)

**Comment by merepapa** [comment]
here i am using 2020
https://drive.google.com/file/d/1AhJ-WqGJX4Nb_Mvmu_nK0g8sHPB1fbId/view?usp=sharing

**Comment by Eliepse** [comment]
Hello, good news! I just created a new version of the script. I tested it on your file and it works.

I guess it's a little late... Sorry for the delay, hope you've been able to find a workaround.
